# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hy99ee/Dev/projects/pyProject_2.1_iaa/MainWindow/forms_ui/InputDataEditor.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(538, 288)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbAccept = QtWidgets.QPushButton(Dialog)
        self.pbAccept.setMaximumSize(QtCore.QSize(16777215, 34))
        self.pbAccept.setObjectName("pbAccept")
        self.horizontalLayout.addWidget(self.pbAccept)
        self.pbClose = QtWidgets.QPushButton(Dialog)
        self.pbClose.setMaximumSize(QtCore.QSize(16777215, 34))
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout.addWidget(self.pbClose)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.stage2 = QtWidgets.QFrame(Dialog)
        self.stage2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stage2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stage2.setObjectName("stage2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.stage2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.windowSize = QtWidgets.QSpinBox(self.stage2)
        self.windowSize.setMinimumSize(QtCore.QSize(0, 34))
        self.windowSize.setMaximumSize(QtCore.QSize(16777215, 34))
        self.windowSize.setMinimum(1)
        self.windowSize.setMaximum(9)
        self.windowSize.setProperty("value", 3)
        self.windowSize.setObjectName("windowSize")
        self.horizontalLayout_2.addWidget(self.windowSize)
        self.label_2 = QtWidgets.QLabel(self.stage2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 34))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.pbDefaultWin = QtWidgets.QPushButton(self.stage2)
        self.pbDefaultWin.setObjectName("pbDefaultWin")
        self.gridLayout_4.addWidget(self.pbDefaultWin, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.stage2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.stage1 = QtWidgets.QStackedWidget(Dialog)
        self.stage1.setObjectName("stage1")
        self.start1 = QtWidgets.QWidget()
        self.start1.setObjectName("start1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.start1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.data1 = QtWidgets.QLineEdit(self.start1)
        self.data1.setMinimumSize(QtCore.QSize(0, 34))
        self.data1.setMaximumSize(QtCore.QSize(16777215, 34))
        self.data1.setObjectName("data1")
        self.gridLayout_2.addWidget(self.data1, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.start1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        self.stage1.addWidget(self.start1)
        self.start2 = QtWidgets.QWidget()
        self.start2.setObjectName("start2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.start2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pbClean = QtWidgets.QPushButton(self.start2)
        self.pbClean.setObjectName("pbClean")
        self.gridLayout_3.addWidget(self.pbClean, 2, 1, 1, 1)
        self.pbOpenDialog = QtWidgets.QPushButton(self.start2)
        self.pbOpenDialog.setObjectName("pbOpenDialog")
        self.gridLayout_3.addWidget(self.pbOpenDialog, 2, 0, 1, 1)
        self.dialogData = QtWidgets.QLineEdit(self.start2)
        self.dialogData.setObjectName("dialogData")
        self.gridLayout_3.addWidget(self.dialogData, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.start2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.start2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.sbVariant = QtWidgets.QSpinBox(self.start2)
        self.sbVariant.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sbVariant.setMinimum(1)
        self.sbVariant.setMaximum(30)
        self.sbVariant.setProperty("value", 7)
        self.sbVariant.setObjectName("sbVariant")
        self.horizontalLayout_4.addWidget(self.sbVariant)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.stage1.addWidget(self.start2)
        self.gridLayout.addWidget(self.stage1, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stage1.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pbAccept.setText(_translate("Dialog", "Принять"))
        self.pbClose.setText(_translate("Dialog", "Выход"))
        self.windowSize.setToolTip(_translate("Dialog", "Минимальное значение для расчета EMA = \"2\""))
        self.label_2.setToolTip(_translate("Dialog", "Минимальное значение для расчета EMA = \"2\""))
        self.label_2.setText(_translate("Dialog", "Введите размер окна"))
        self.pbDefaultWin.setText(_translate("Dialog", "По умолчанию"))
        self.data1.setToolTip(_translate("Dialog", "Введите числа для подсчета энтропии через \",\""))
        self.label.setText(_translate("Dialog", "Введите данные для подсчета энтропии:"))
        self.pbClean.setText(_translate("Dialog", "Очистить"))
        self.pbOpenDialog.setText(_translate("Dialog", "Выбрать файл"))
        self.label_3.setText(_translate("Dialog", "Выберете файл для вычисления средней:"))
        self.label_5.setText(_translate("Dialog", "Вариант №:"))
